### ISSUE TITLE
请问占据边缘的障碍，可以处理吗

### ISSUE THREAD

**Issue by 15951836388** [huskar-t/NavMeshPathFinding#2]
![image](https://user-images.githubusercontent.com/14047483/80678900-646dfa00-8aee-11ea-9b8d-9b3956a99053.png)
这个矩形，向右便宜了一个像素，才行

如果正好在边界，这个碰撞矩形就被忽略了

**Comment by huskar-t** [comment]
按照描述我做了一个测试(图上粉色线为生成的狄洛尼三角网,四周边界向内缩了小球半径,障碍物边界向外扩小球半径)障碍物一个边界线与四周边界线重合,可以发现障碍物并没有被忽略，而是四周边界被切断向障碍物边界合批
![image](https://user-images.githubusercontent.com/26872926/80680700-d85dd180-8af1-11ea-90ad-0b44081ce10c.png)

**Comment by 15951836388** [comment]
chorm打开不了你的测试demo地址

原始的碰撞数据
![image](https://user-images.githubusercontent.com/14047483/80681912-2b388880-8af4-11ea-8e78-d33e8212c1e4.png)

生成的三角形网格，没有吧这个超过边界碰撞算进去。即使我把这个矩形裁成和左边边界一样大，也不行
![image](https://user-images.githubusercontent.com/14047483/80681936-34c1f080-8af4-11ea-885e-f1b7c001d1b0.png)

**Comment by huskar-t** [comment]
只能计算边界内的障碍，可以把计算范围放大到边界外，然后将边界外区域都设置为障碍物

**Comment by 15951836388** [comment]
有没有办法做到，如果边界有障碍，“边界被切断向障碍物边界合批”？
因为地图一般是策划来摆放，尽量不用过多规则限制策划是最好的了

**Comment by huskar-t** [comment]
临时写了一个障碍物边界截断边界外忽略pull一下最新的试试

**Comment by 15951836388** [comment]
嗯，自动忽略功能，本身没有问题。
但一般的实际情况是，策划在边界上摆了一块大石头，要求这块石头在地图内的部分都是要有碰撞的。
也就是说能自动，裁切成类似这样的才行
![image](https://user-images.githubusercontent.com/14047483/81464107-8acc1d80-91f1-11ea-88a5-03b0ef4776b2.png)

**Comment by huskar-t** [comment]
已经这样实现了，用今天最新的版本试试

**Comment by 15951836388** [comment]
我用了新版的，没有达到上面的效果

**Comment by huskar-t** [comment]
![image](https://user-images.githubusercontent.com/26872926/81464377-c0720600-91f3-11ea-9af1-0ae5fa2357c5.png)
我的测试效果如图

**Comment by 15951836388** [comment]
1.碰撞矩形，在左边界无效果（其他三条边有效果）在左上角，程序报错 

2.在右边界

注意下面2个碰撞矩形的排布

这种排列情况会崩溃（上面一个碰撞矩形比较靠外）
![image](https://user-images.githubusercontent.com/14047483/81465216-efd84100-91fa-11ea-962c-74f9cccf1a1c.png)

这种情况，没有崩溃，但是碰撞不对
![image](https://user-images.githubusercontent.com/14047483/81465360-3d08e280-91fc-11ea-92af-562289420656.png)
