### ISSUE TITLE
有时候找出的路线，明显绕远了

### ISSUE THREAD

**Issue by 15951836388** [huskar-t/NavMeshPathFinding#3]
从图中1位置到2位置

![image](https://user-images.githubusercontent.com/14047483/80681378-2c1cea80-8af3-11ea-8b68-4d3eed913a77.png)

**Comment by huskar-t** [comment]
这个算法不是最优算法，只能是近似，如果有太扁的三角形取中心点会有很大的偏差，可以在生成三角网之后自己实现一个A*寻路
